@echo off
echo Activating virtual environment...
call myenv\Scripts\activate

echo Installing pytest (if not installed)...
call pip install pytest

echo Running pytest for all arithmetic tests...
call python -m pytest -s -v  

echo Deactivating virtual environment...
call myenv\Scripts\deactivate.bat
pause
